
// @ts-nocheck
// This file is autogenerated by Firebase App Hosting.
// Do not edit this file.

// This file is intended to be used by the Firebase JS SDKs.
const firebaseConfig = {
  "projectId": "agenda-news-room-4491522-e400a",
  "appId": "1:363314732473:web:de90e196a1961d1c646a68",
  "storageBucket": "agenda-news-room-4491522-e400a.firebasestorage.app",
  "apiKey": "AIzaSyAvMXEWfRiGaZfMf3LLdvbG0waaXEbh4Mg",
  "authDomain": "agenda-news-room-4491522-e400a.firebaseapp.com",
  "messagingSenderId": "363314732473"
};

export { firebaseConfig };
